const common = {
  locale: "tr",
  ogLocale: "tr_TR",
  language: "Türkçe",
  market: "Türkiye",
  nav: [
    ["Ana Sayfa", "/"], ["Ürünler", "/products/"], ["Uygulamalar", "/applications/"],
    ["Kalite Kontrol", "/quality-control/"], ["Teknik Belgeler", "/technical-documents/"],
    ["Ambalaj ve Teslimat", "/packaging-delivery/"], ["Kaynaklar", "/blog/"], ["İletişim", "/contact/"],
  ],
  ui: {
    quote: "Fiyat Teklifi Al", sample: "Numune Talep Et", documents: "Teknik Föy Talep Et", learnMore: "İncele",
    contact: "İletişime Geç", products: "Ürünleri Gör", applications: "Uygulamaları Gör", home: "Ana Sayfa",
    skip: "İçeriğe geç", menu: "Menü", language: "Dil seçin",
    formTitle: "İhtiyacınızı paylaşın",
    formIntro: "Kaynak, hedef PS oranı, uygulama ve tahmini miktarı gönderin; ekip uygunluk ve belge kapsamını kontrol etsin.",
    success: "Talebiniz alındı. Ekibimiz inceleyip sizinle iletişime geçecektir.",
    error: "Talep gönderilemedi. Lütfen e-posta veya WhatsApp üzerinden doğrudan iletişime geçin.",
    required: "Lütfen zorunlu alanları kontrol edin.", submitting: "Gönderiliyor…",
    footer: "Takviye edici gıda ve fonksiyonel gıda geliştirme ekipleri için fosfatidilserin B2B hammadde bilgileri.",
    legal: "Uygunluk, etiketleme ve mevzuat gereklilikleri hedef pazar ile nihai kullanım temelinde alıcı tarafından değerlendirilmelidir.",
  },
};

const pages = [
  {
    route: "/", type: "home", image: "product-powder-spoon.webp",
    title: "Fosfatidilserin Üreticisi ve Tedarikçisi | Takviye Edici Gıda",
    description: "Soya ve ayçiçeği kaynaklı fosfatidilserin hammaddelerini teknik belgeler, numune desteği ve toplu tedarik hizmetiyle sunuyoruz.",
    h1: "Takviye Edici Gıdalar İçin Fosfatidilserin Üreticisi ve Tedarikçisi",
    intro: "Soya ve ayçiçeği kaynaklı fosfatidilserin hammaddelerini teknik belgeler, numune desteği ve toplu tedarik hizmetiyle sunuyoruz.",
    sections: [
      ["Türkiye pazarına tedarik deneyimi", "Takviye markaları, üreticiler, ithalatçılar, distribütörler ve bölgesel ticaret şirketleri için B2B satın alma görüşmeleri yürütüyoruz. Müşteri ve sipariş bilgileri açıklanmaz."],
      ["Soya ve ayçiçeği kaynakları", "Ürün konsepti, alerjen yaklaşımı ve hedef PS oranına göre hammadde kaynağı seçeneklerini değerlendirin."],
      ["Teknik belge ve numune desteği", "COA, spesifikasyon, TDS, SDS ve kaynak beyanlarının mevcut kapsamı ürün bazında doğrulanır."],
      ["Toplu tedarik ve distribütör görüşmeleri", "Tahmini miktar, hedef ülke, ambalaj ve teslimat koşullarını paylaşarak ticari değerlendirme talep edebilirsiniz."],
    ],
  },
  {
    route: "/about/", title: "Nutranexa Hakkında | Fosfatidilserin Hammadde Ortağı",
    description: "Nutranexa'nın fosfatidilserin ürün kapsamını, belge odaklı tedarik yaklaşımını ve Türkiye alıcıları için iletişim sürecini inceleyin.",
    h1: "PS hammadde değerlendirmesini belge ve uygulama ihtiyacıyla başlatın",
    intro: "Nutranexa; takviye markaları, üreticiler, ithalatçılar ve distribütörlerin fosfatidilserin tedarikçi değerlendirmesini destekler.",
    sections: [
      ["B2B satın alma odağı", "Kaynak, hedef oran, dozaj formu, gerekli belgeler, tahmini miktar ve varış ülkesini tek bir değerlendirmede toplarız."],
      ["Doğrulanmış bilgi yaklaşımı", "Sertifika kapsamı, spesifikasyon, MOQ, teslim süresi ve mevzuat durumu ürün ile sipariş koşullarına göre doğrulanmadan kesin vaat olarak sunulmaz."],
      ["Tekrarlı sipariş planlaması", "Parti belgeleri, değişiklik bildirimi, ambalaj ve sevkiyat gereklilikleri uzun vadeli satın alma sürecine dahil edilebilir."],
    ],
  },
  {
    route: "/contact/", type: "form", formKind: "contact",
    title: "Fosfatidilserin Hammadde İletişim | Nutranexa",
    description: "PS hammaddesi, COA, spesifikasyon, numune, OEM uygulaması veya distribütörlük hakkında Türkçe talep gönderin.",
    h1: "Fosfatidilserin hammadde talebinizi gönderin",
    intro: "İstenen kaynak, oran, uygulama, miktar ve belgeleri paylaşın; ekip mevcut seçenekleri kontrol etsin.",
  },
  {
    route: "/quote/", type: "form", formKind: "quote",
    title: "Fosfatidilserin Fiyat Teklifi | Toplu PS Hammaddesi",
    description: "Soya veya ayçiçeği kaynaklı PS için hedef oran, miktar, ambalaj, varış ülkesi ve belge ihtiyaçlarıyla fiyat teklifi isteyin.",
    h1: "Toplu fosfatidilserin fiyat teklifi alın",
    intro: "Doğru ticari değerlendirme için kaynak, hedef PS oranı, tahmini miktar, varış ülkesi ve gerekli belgeleri belirtin.",
  },
  {
    route: "/sample-request/", type: "form", formKind: "sample",
    title: "Fosfatidilserin Numunesi Talep Et | Ürün Geliştirme",
    description: "Kapsül, tablet, toz, içecek, gummy ve fonksiyonel gıda geliştirme çalışmaları için PS hammadde numunesi isteyin.",
    h1: "Fosfatidilserin hammadde numunesi talep edin",
    intro: "Numunenin kullanım amacı, ürün formatı, hedef oran ve sonraki satın alma planını paylaşarak uygunluk kontrolü isteyin.",
  },
  {
    route: "/quality-control/",
    title: "Fosfatidilserin Kalite Kontrol | COA ve Spesifikasyon",
    description: "PS oranı, kaynak, mikrobiyoloji, ağır metaller, kalıntı çözücüler ve oksidasyonla ilgili kalite belge kontrol başlıklarını inceleyin.",
    h1: "PS hammadde kalite kontrolü ve lot belge incelemesi",
    intro: "Satın alma öncesi spesifikasyon mutabakatı ve lot bazlı belge kontrolü için temel başlıkları netleştirin.",
    sections: [
      ["PS oranı ve test yöntemi", "Hedef fosfatidilserin oranı ile kullanılan analiz yöntemi ürün spesifikasyonu ve COA üzerinde doğrulanmalıdır."],
      ["Güvenlik parametreleri", "Mikrobiyoloji, ağır metaller, kalıntı çözücüler ve diğer gereklilikler alıcı spesifikasyonuyla karşılaştırılır."],
      ["Kaynak ve alerjen belgeleri", "Soya veya ayçiçeği kaynağı ile GMO ve alerjen beyanlarının kapsamı ürün bazında kontrol edilir."],
      ["Parti tutarlılığı ve değişiklik bildirimi", "Tekrarlı siparişlerde kaynak, proses, spesifikasyon veya ambalaj değişikliklerinin bildirim şartları önceden tanımlanmalıdır."],
    ],
  },
  {
    route: "/technical-documents/",
    title: "Fosfatidilserin Teknik Belgeleri | COA, TDS ve SDS",
    description: "PS hammaddesi için COA, spesifikasyon, TDS, SDS, GMO ve alerjen beyanı talep edin; mevcut belge kapsamını doğrulayın.",
    h1: "Fosfatidilserin teknik belgelerini talep edin",
    intro: "Belge kapsamı ürüne, lota, hedef ülkeye ve kullanıma göre değişebilir; talebinizde gereken dosyaları seçin.",
    sections: [
      ["Kalite dosyası", "COA, ürün spesifikasyonu ve analiz başlıkları ilgili ürün ve lot için kontrol edilir."],
      ["Teknik ve güvenlik dokümanları", "TDS ve SDS dosyalarının güncel sürümü ile kapsamı talep sırasında doğrulanır."],
      ["Kaynak beyanları", "GMO, alerjen, soya veya ayçiçeği kaynağına ilişkin belge bulunabilirliği ürün bazında kontrol edilir."],
      ["Mevzuat değerlendirmesi", "Belge sağlanması nihai ürün için mevzuat onayı anlamına gelmez. LEGAL REVIEW REQUIRED."],
    ],
  },
  {
    route: "/packaging-delivery/",
    title: "PS Ambalaj ve Uluslararası Teslimat | Satın Alma Kontrolü",
    description: "Fosfatidilserin hammaddesinin ambalaj, etiket, palet, sevkiyat belgesi ve uluslararası lojistik gerekliliklerini doğrulayın.",
    h1: "Ambalaj ve uluslararası teslimat gerekliliklerini planlayın",
    intro: "Ambalaj birimi, teslim süresi, ticari teslim şekli ve hedef ülke belgeleri gerçek sipariş koşullarına göre teklif aşamasında doğrulanır.",
    sections: [
      ["Ambalaj spesifikasyonu ve MOQ", "Standart MOQ 25 kg, 1 varildir. İç ve dış ambalaj, net ağırlık ve etiket talepleri ürün ile sipariş bazında son kez doğrulanır."],
      ["Sevkiyat belgeleri", "Ticari fatura, paketleme listesi, COA ve hedef ülkenin istediği evrak sipariş öncesinde karşılaştırılır."],
      ["Uluslararası lojistik", "Incoterms, taşıma yöntemi, süre ve maliyet; varış yeri, miktar ve güncel taşıma koşullarına göre ayrıca teyit edilir."],
    ],
  },
  {
    route: "/faq/", type: "faq",
    title: "Fosfatidilserin Hammadde SSS | Fiyat, Numune ve Belgeler",
    description: "Soya ve ayçiçeği kaynaklı PS, oran, numune, COA, MOQ, ambalaj, ithalat ve OEM uygulamaları hakkında sık sorulan sorular.",
    h1: "Fosfatidilserin hammadde sık sorulan sorular",
    intro: "Türkiye'deki B2B alıcıların ilk tedarikçi değerlendirmesinde sıkça kontrol ettiği konular.",
    faq: [
      ["Soya ve ayçiçeği kaynaklı PS seçenekleri var mı?", "Her iki kaynak için talep gönderebilirsiniz. Gerçek tedarik kapsamı hedef oran ve sipariş koşullarına göre doğrulanır."],
      ["PS 20%, 50%, 70% ve 80% ürünlerin tümü mevcut mu?", "20% ve 50% dahil ihtiyaç duyulan oran sorulabilir. 70% ve 80% gibi diğer oranlar teyit edilmeden kesin ürün olarak yayınlanmaz."],
      ["Numune ile birlikte COA isteyebilir miyim?", "Evet. Numunenin uygulamasını, hedef oranı ve gerekli belgeleri formda belirtin."],
      ["MOQ ve teslim süresi nedir?", "Standart MOQ 25 kg, 1 varildir. Teslim süresi ve taşıma koşulları ürün, oran ve hedef ülkeye göre teklif aşamasında doğrulanır."],
      ["Ürün Türkiye mevzuatına uygun mu?", "Hammadde belgeleri sağlanabilir; nihai ürün uygunluğu ithalatçı ve ürün sorumlusu tarafından değerlendirilmelidir. LEGAL REVIEW REQUIRED."],
      ["Distribütörlük görüşmesi yapabilir miyiz?", "Hedef bölge, müşteri grubu ve tahmini hacmi paylaşarak distribütörlük değerlendirmesi talep edebilirsiniz; münhasırlık veya temsilcilik önceden vaat edilmez."],
    ],
  },
  {
    route: "/blog/", type: "blog",
    title: "Fosfatidilserin Satın Alma Rehberi | Türkiye B2B Kaynakları",
    description: "Türkiye'deki takviye üreticileri, ithalatçılar ve distribütörler için PS hammadde satın alma ve belge kontrol konuları.",
    h1: "PS hammadde satın alma ve ürün geliştirme kaynakları",
    intro: "İlk içerikler tedarikçi seçimi, kaynak karşılaştırması, belge kontrolü, fiyat ve numune değerlendirmesine odaklanır.",
    articles: [
      ["Fosfatidilserin hammaddesi nedir?", "Kaynak, oran ve B2B satın almada kontrol edilecek temel başlıklar."],
      ["Soya ve ayçiçeği kaynaklı PS karşılaştırması", "Kaynak, alerjen belgesi ve ürün konumlandırması açısından seçim."],
      ["PS tedarikçisi belge kontrol listesi", "COA, spesifikasyon, TDS, SDS ve beyan dosyalarının kontrol sırası."],
      ["Numuneden toplu siparişe geçiş", "Formül denemesi, belge onayı, ambalaj ve tekrarlı sipariş adımları."],
    ],
  },
  {
    route: "/products/", type: "products",
    title: "Fosfatidilserin Ürünleri | Soya ve Ayçiçeği Kaynaklı PS",
    description: "Soya kaynaklı PS, ayçiçeği kaynaklı PS ve hedef oranlara göre fosfatidilserin hammadde seçeneklerini inceleyin.",
    h1: "Fosfatidilserin hammadde ürünleri",
    intro: "Kaynak, hedef oran, dozaj formu ve belge gereksinimlerine göre ürün değerlendirmesi yapın.",
  },
  {
    route: "/products/soy-phosphatidylserine/", type: "product", image: "product-soy-ps.webp",
    title: "Soya Kaynaklı Fosfatidilserin Üreticisi ve Tedarikçisi",
    description: "Kapsül, tablet, toz ve fonksiyonel gıda geliştirme için soya kaynaklı fosfatidilserin hammaddesi, numune ve belge talep edin.",
    h1: "Soya kaynaklı fosfatidilserin hammaddesi",
    intro: "Soya kaynaklı PS için hedef oran, ürün formatı, GMO ve alerjen belge ihtiyaçlarını birlikte değerlendirin.",
    sections: [["Uygulama alanları", "Kapsül, tablet, toz, katı içecek ve fonksiyonel gıda gibi farklı ürün formatları için değerlendirilebilir."], ["Satın alma kontrolü", "PS oranı, analiz yöntemi, soya kaynağı, alerjen etiketi ve gerekli belgeler sipariş öncesinde doğrulanır."]],
  },
  {
    route: "/products/sunflower-phosphatidylserine/", type: "product", image: "product-sunflower-ps.webp",
    title: "Ayçiçeği Kaynaklı Fosfatidilserin Üreticisi ve Tedarikçisi",
    description: "Soya içermeyen ürün konseptleri için ayçiçeği kaynaklı fosfatidilserin hammaddesi, numune ve teknik belge talep edin.",
    h1: "Ayçiçeği kaynaklı fosfatidilserin hammaddesi",
    intro: "Ayçiçeği kaynaklı PS arayan marka ve üreticiler için hedef oran, kaynak belgesi ve uygulama ihtiyacını doğrulayın.",
    sections: [["Kaynak odaklı ürün geliştirme", "Soya kullanımını sınırlayan ürün konseptlerinde ayçiçeği kaynağı ve ilgili beyanlar ürün bazında kontrol edilir."], ["Numune ve belge", "Numune, COA, spesifikasyon ve kaynak beyanlarının mevcut kapsamı talep edilebilir."]],
  },
  {
    route: "/products/ps-specifications/",
    title: "Fosfatidilserin Oranları ve Spesifikasyon | PS 20% ve 50%",
    description: "PS 20%, PS 50% ve diğer hedef oranlar için kaynak, analiz yöntemi, COA, fiziksel özellikler ve uygulama gereksinimlerini karşılaştırın.",
    h1: "PS oranı ve ürün spesifikasyonu değerlendirmesi",
    intro: "Güncel ve paylaşılabilir spesifikasyonlar talep sırasında doğrulanır; zayıf oran sayfaları yerine satın alma karşılaştırma başlıkları sunulur.",
    sections: [["Talep edilebilen oranlar", "PS 20% ve PS 50% dahil hedef oranınızı belirtin. 70% ve 80% seçenekleri gerçek bulunabilirlik doğrulanmadan kesin ürün olarak gösterilmez."], ["MOQ ve spesifikasyon karşılaştırması", "Standart MOQ 25 kg, 1 varildir. Oranın yanında kaynak, test yöntemi, fiziksel özellikler, mikrobiyoloji, ağır metal limitleri, ambalaj ve uygulama birlikte değerlendirilir."]],
  },
  {
    route: "/applications/", type: "applications",
    title: "Fosfatidilserin Uygulamaları | Takviye, Fonksiyonel Gıda ve OEM",
    description: "Kapsül, tablet, toz, katı içecek, fonksiyonel gıda, gummy, içecek ve OEM ürünleri için PS uygulamalarını inceleyin.",
    h1: "Fosfatidilserin hammadde uygulamaları",
    intro: "Nihai ürün formatı, hedef oran, proses koşulları ve pazar belgelerine göre hammadde uygunluğunu değerlendirin.",
  },
  {
    route: "/applications/dietary-supplements/",
    title: "Takviye Edici Gıdalar İçin Fosfatidilserin Hammaddesi",
    description: "Kapsül, tablet ve toz takviye geliştirme için PS hammadde kaynağı, oranı, numune ve teknik belgelerini değerlendirin.",
    h1: "Takviye edici gıda geliştirme için PS hammaddesi",
    intro: "Bilişsel sağlık ve hafıza desteği odaklı beslenme ürünlerinde kullanılacak hammadde için format ve belge gereksinimlerini inceleyin.",
    sections: [["Dozaj formu değerlendirmesi", "Kapsül, tablet, toz ve katı içecek formülasyonlarında proses uygunluğu nihai ürün geliştiricisi tarafından gerçek denemelerle doğrulanmalıdır."], ["Etiket ve mevzuat", "Sağlık beyanları ile etiket metni hedef pazar kurallarına göre ayrıca incelenmelidir. LEGAL REVIEW REQUIRED."]],
  },
  {
    route: "/applications/functional-foods/",
    title: "Fonksiyonel Gıdalar İçin Fosfatidilserin Hammaddesi",
    description: "Fonksiyonel gıda, içecek, toz ve sağlıklı yaşlanma ürünleri için PS hammadde uygulama ve numune değerlendirmesi yapın.",
    h1: "Fonksiyonel gıda ve içecekler için PS hammaddesi",
    intro: "Ürün matrisi, proses, duyusal özellik ve stabilite beklentilerine göre numune değerlendirme planı oluşturun.",
    sections: [["Ürün matrisi", "Toz, katı içecek, fonksiyonel gıda, gummy ve içeceklerde dağılma, tat, renk ve stabilite gerçek formülde test edilmelidir."], ["Dikkatli konumlandırma", "Beyin sağlığı, bilişsel sağlık veya sağlıklı yaşlanma konseptlerinde değerlendirilebilir; hastalık tedavi veya önleme iddiası kullanılmaz."]],
  },
  {
    route: "/applications/oem-odm/",
    title: "OEM Üretimi İçin Fosfatidilserin Hammaddesi",
    description: "Türkiye'deki OEM üreticileri için PS numunesi, spesifikasyon, COA, uygulama ve satın alma aktarım desteği talep edin.",
    h1: "OEM ürün geliştirme ekipleri için PS hammadde desteği",
    intro: "Kaynak ve oran seçiminden numune, belge onayı ve satın alma aktarımına kadar gerekli bilgileri tek dosyada toplayın.",
    sections: [["Geliştirme özeti", "Hedef format, günlük kullanım tasarımı, kaynak, hedef oran ve pazar paylaşıldığında hammadde değerlendirmesi daha verimli olur."], ["Satın alma aktarımı", "Onaylanan numune, spesifikasyon, belge sürümü, ambalaj ve değişiklik bildirim koşullarını satın alma gerekliliğine dönüştürün."]],
  },
];

export default { ...common, pages };
